### ISSUE TITLE
Grouping by Service

### ISSUE THREAD

**Issue by Japh** [dnavarrom/aws-cost-explorer#2]
Sorry if this is documented somewhere and I just can't find it, but I don't see how to group by service currently. Mainly I'm unsure what to pass as the `Key`, assuming I can set the `Type` to `SERVICE`.

Any assistance appreciated!

**Comment by dnavarrom** [comment]
Yes, you can found an example on #6. I've just created a folder to put those examples on [examples](https://github.com/dnavarrom/aws-cost-explorer/tree/master/examples)
